apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.app.name }}
  annotations:
    secrets.doppler.com/reload: 'true'
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.container.name }}
          image: {{ .Values.app.container.image }}
          {{- if .Values.app.container.command }}
          command: {{- range .Values.app.container.command }}
            - {{ . }} {{- end}}
              {{- end}}
          {{- end }}
          ports:
            - containerPort: {{ .Values.app.container.port }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          {{- if .Values.secrets }}
          envFrom:
            {{- range .Values.secrets }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}
          {{- if .Values.app.container.env }}
          env:
            {{- range .Values.app.container.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.volumes.enabled }}
          volumeMounts:
            {{- range .Values.volumes.items }}
            - mountPath: {{.mountPath}}
              name: {{.name}}
            {{- end}}
          {{- end }}
      {{- if .Values.volumes.enabled }}
      volumes:
        {{- range .Values.volumes.items }}
        - name: {{.name}}
          persistentVolumeClaim:
            claimName: {{.persistentVolumeClaimName}}
        {{- end }}
      {{- end }}
