{{- if .Values.persistentVolumeClaims.enabled}}
{{- range .Values.persistentVolumeClaims.items}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.name}}
  namespace: {{ $.Values.app.namespace }}
  labels:
    app: {{ $.Values.app.name }}
spec:
  storageClassName: {{ .storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.storageCapacity}}

---

{{- end}}
{{- end}}