apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.app.name }}
  annotations:
    secrets.doppler.com/reload: "true"
spec:
  selector:
    matchLabels:
      run: {{ .Values.app.name }}
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        run: {{ .Values.app.name }}
    spec:
      restartPolicy: {{ .Values.app.restartPolicy | default "Always" | quote }}
      containers:
      {{- range $index, $container := .Values.app.container }}
        - name: {{ $container.name | default $.Values.app.name }}
          image: {{ $container.image }}
          ports:
            - containerPort: {{ $container.port }}
          imagePullPolicy: {{ $container.imagePullPolicy }}

          {{- if $container.secret }}
          envFrom:
            - secretRef:
                name: {{ $container.secret }}
          {{- end}}

          {{- if $container.env }}
          env:
            {{- range $envIndex, $env := $container.env }}
            - name: {{ $env.name }}
              value: {{ $env.value | quote }}
            {{- end }}
          {{- end }}
      {{- end}}

      
