apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  annotations:
    secrets.doppler.com/reload: 'true'
spec:
  schedule: {{ .Values.app.schedule }}
  timeZone: {{ .Values.app.timeZone | default "Etc/UTC" | quote }}
  suspend: {{ .Values.app.suspend | default false }}
  successfulJobsHistoryLimit: {{ .Values.app.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.app.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.app.container.name }}
              image: {{ .Values.app.container.image }}
              imagePullPolicy: {{ .Values.app.container.imagePullPolicy | default "Always" }}
              {{- if .Values.app.container.command }}
              command: {{ .Values.app.container.command }}
              {{- end}}
              envFrom:
              - secretRef:
                  name: {{ .Values.secrets.dopplerSecretName }}
          restartPolicy: OnFailure
