app:
  namespace: backend
  name: test
  replicas: 1
  selector:
    run: test
  container:
    name: test
    image: test
    port: 8080
secrets:
  dopplerSecretName:
service:
  name: default
  enabled: true
ingress:
  name: test
  host: test
  path: test
  is_root: true
  enabled: true
