app:
  name: test
  namespace: backend
  replicas: 1
  selector:
    run: test
  container:
    name: test
    image: test
    port: 8080
secrets:
  dopplerSecretName: secret-name
service:
  name: default
  enabled: true
ingress:
  name: test
  host: test
  path: test
  is_root: true
  enabled: true
persistentVolumes:
  enabled: true
  items:
  - name: pv-01
    storageCapacity: 10Gi
    storageClassName: manual
    hostPath: "/mnt/data"
    type: local
persistentVolumeClaims:
  enabled: true
  items:
    - name: pvc-01
      storageCapacity: 10Gi
      storageClassName: manual
volumes:
  enabled: true
  items:
    - name: volume-name-1
      mountPath: "/var/lib/..."
      persistentVolumeClaimName: pvc-01
