app:
  name: test
  namespace: backend
  replicas: 1
  selector:
    run: test
  container:
    name: test
    image: test
    port: 8080
secrets:
  dopplerSecretName: secret-name
service:
  name: default
  enabled: true
ingress:
  name: test
  host: test
  path: test
  is_root: true
  enabled: true
persistentVolume:
  enabled: true
  storageCapacity: 10Gi
  type: local
  storageClassName: manual
  hostPath: "/mnt/data"
volumes:
  enabled: true
  items:
    - name: volume-name
      mountPath: "/var/lib/..."
      persistentVolumeClaimName: volume-pvc-name
