app:
  namespace:
  name: 
  replicas: 1
  selector:
    run: 
  container:
    name: 
    image: 
    port: 8080
secrets:
  dopplerSecretName:
service:
  name: default
ingress:
  name: 
  host: 
  path: 
  enabled: true
