{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app.name }}-pv
  labels:
    type: {{ .Values.persistentVolume.type }}
    app: {{ .Values.app.name }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.storageCapacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
{{- end}}