{{- if .Values.persistentVolumes.enabled }}
{{- range .Values.persistentVolumes.items }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
  labels:
    type: {{ .type }}
    app: {{ $.Values.app.name }}
spec:
  storageClassName: {{ .storageClassName }}
  capacity:
    storage: {{ .storageCapacity }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .hostPath }}

---
{{- end}}
{{- end}}