{{- if .Values.persistentVolume.enabled}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-pvc
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{.Values.app.name}}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.persistentVolume.storageCapacity}}
{{- end}}