{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports}}
    - port: {{ .port }}
      type: {{ .type | default "ClusterIP" | quote }}
      {{- if .name }}
      name: {{ .name }}
      {{- end}}
      targetPort: {{ .targetPort }}
      {{- if eq .type "NodePort" }}
      nodePort: {{ .nodePort }}
      {{- end}}
      {{- if .protocol}}
      protocol: {{ .protocol }}
      {{- end}}
    {{- end}}
  selector:
    app: {{ .Values.service.appSelector }}
{{ end }}