app:
  name: my-app
  namespace: backend
  restartPolicy: Always
  replicas: 1
  container:
    name: container-app
    image: ""
    port: 8080
    imagePullPolicy: Always
    secret: ""
    env: []
  livenessProbe:
    enabled: false
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 3
  readinessProbe:
    enabled: false
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
  startupProbe:
    enabled: false
    httpGet:
      path: /health
      port: liveness-port
    failureThreshold: 30
    periodSeconds: 10

service:
  enabled: true
  ports:
    - type: ClusterIP
      name: http
      port: 80
      targetPort: 8080
      nodePort: 30000
      protocol: TCP

ingress:
  enabled: true
  ingressClassName: nginx
  tls:
    - hosts:
        - example.com.br
      secretName: example-tls
  rule:
    host: example.com.br
    path: /
    pathType: ImplementationSpecific