app:
  name: my-app
  namespace: backend
  replicas: 1
  imagePullPolicy: Always
  container:
    name: test
    image: test
    port: 8080
    command: ["sh", "-c", "echo hello"]
    env: []
secrets:
  - name: secret-name
  - name: secret-name-2
service:
  enabled: false
  name: app-service
  appSelector: test
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
ingress:
  enabled: false
  name: test
  host: test
  path: "/"
persistentVolumes:
  enabled: false
  items:
  - name: pv-01
    storageCapacity: 10Gi
    storageClassName: manual
    hostPath: "/mnt/data"
    type: local
persistentVolumeClaims:
  enabled: false
  items:
    - name: pvc-01
      storageCapacity: 10Gi
      storageClassName: manual
volumes:
  enabled: false
  items:
    - name: volume-name-1
      mountPath: "/var/lib/..."
      persistentVolumeClaimName: pvc-01
