app:
  namespace: backend
  name: simple-cronjob
  schedule: 0 */4 * * *
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  timeZone: America/Sao_Paulo
  suspend: false
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  container:
    name: container-name
    image: container-image
    imagePullPolicy: IfNotPresent
    command:
      - /bin/sh
      - -c
      - echo "Hello, World!"
secrets:
  dopplerSecretName: secret-name
